### ISSUE TITLE
Add to homebrew-core or other tap

### ISSUE THREAD

**Issue by tony-sol** [macmade/QEMU-Manager#14]

**Comment by tony-sol** [comment]
well, i guess it should be "Closed as not planned", but missclick or something

**Comment by macmade** [comment]
Maybe next time try to spend some time writing a good issue if you want something to be made…

**Comment by tony-sol** [comment]
Maybe download button on https://xs-labs.com/en/apps/qemu-manager/overview/ should work, for not searching this in external resources.

Anyway, i already started to make a cask for you, but looks like there is no interest in it, 'cause releases are empty, tags are empty, actions has no build targets.

So, for now there is no way to install app except build from source, and if the owner doesn't care, then all the more so for me.

End of story.

**Comment by macmade** [comment]
There’s is nothing to download because the project is not finished yet.
It has nothing to do with caring or not caring.
How hard is it to understand that?
