### ISSUE TITLE
No Releases

### ISSUE THREAD

**Issue by Alvin-Alford** [macmade/QEMU-Manager#16]
The download link leads to xs-labs which has a download button but their are no releases so nothing to download. Is it possible to make a build of it?

**Comment by macmade** [comment]
Project is not ready for a public build yet.

**Comment by Alvin-Alford** [comment]
how would i build it myself and when will it be public?

**Comment by macmade** [comment]
1. Download Xcode
2. Clone the repository
3. Open the project and build

**Comment by macmade** [comment]
I'm working on other personal projects at the moment, so no public build is planed.

**Comment by Alvin-Alford** [comment]
thanks

**Comment by Alvin-Alford** [comment]
Issue I tried to build it in xcode but it says unable to open configeration settings file

**Comment by macmade** [comment]
You need to clone with submodules
