### ISSUE TITLE
Xcode compile error

### ISSUE THREAD

**Issue by ZenX4005** [macmade/QEMU-Manager#18]
1. /Users/ZenX/GitHub/QEMU-Manager/QEMU-Manager.xcodeproj This Copy Files build phase contains a reference to a missing file 'GitHubUpdates.framework'.
2. Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.
4. /Users/ZenX/GitHub/QEMU-Manager/Submodules/xcconfig/Debug.xcconfig:1:1 unable to open configuration settings file

<img width="1615" alt="Screenshot 2024-01-19 at 10 35 53" src="https://github.com/macmade/QEMU-Manager/assets/76893795/f19974d5-854b-4508-8911-39f432ffb4b9">

**Comment by macmade** [comment]
Update submodules
