### ISSUE TITLE
"task not launched" errors

### ISSUE THREAD

**Issue by jeff-h** [macmade/QEMU-Manager#3]
I built this myself and have been getting "task not launched" errors. I'm wondering if you have ever had these, or might have any thoughts as to what could be causing them?

It's really very odd; [attempts to access](https://github.com/macmade/QEMU-Manager/blob/main/QEMU-Manager/Classes/QEMU/QEMU.swift#L75) the `process.terminationStatus` are resulting in the "task not launched" error. Clearly the process is launched and should `waitUntilExit`. What's most odd is that I added the following debugging code, and the error went away.

```swift
try ObjC.catchException
{
    process.launch()
    process.waitUntilExit()
    let _ = process.terminationStatus
}
```

Unfortunately this only got me past the launch crash. I was able to create a VM but when I double click it in the "QEMU Library" window, I get the error again, and was unable to easily find the code causing it.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/841871/135550958-9d4f636c-258d-4edf-9b2f-6d9ad1bcf484.png">

**Comment by ltecheroffical** [comment]
That one bug is one that is hard to track down

**Comment by rwbutler** [comment]
@jeff-h @ltecheroffical I believe that `ObjC.catchException` accepts a `NSError` in addition to the block which has been supplied. I suspect if you check that error which is returned you would discover that the process could not be launched  (possibly because it cannot be found).

`waitUntilExit` does nothing in this case as the process hasn't been launched. Checking the `terminationStatus` results in the "task not launched" error because indeed in this case the task not been launched.

**Comment by ltecheroffical** [comment]
@rwbutler Maybe it's a good idea to use a direct path but once it is corrected it shows "launch path not accessible"

**Comment by ltecheroffical** [comment]
We can use the system install of qemu to get it working. My suggestion is add a settings pane that you can use to configure settings of the application as well as the qemu path and link the qemu website in case it isn't installed

**Comment by ltecheroffical** [comment]
I fixed the issue by using a direct path, but that won't work assuming so a settings menu is peferred

**Comment by macmade** [comment]
You may want to check this: https://github.com/macmade/QEMU-Manager/issues/9

**Comment by ltecheroffical** [comment]
> You may want to check this: #9

I would recommend not forcing users to build the project so when it is finished we can use the releases, not be forced to build from source. Allowing users to set binaries without rebuilding the project works better and the app is lacking a settings menu and that could be helpful as well.

**Comment by macmade** [comment]
> > You may want to check this: #9
> 
> I would recommend not forcing users to build the project so when it is finished we can use the releases, not be forced to build from source. Allowing users to set binaries without rebuilding the project works better and the app is lacking a settings menu and that could be helpful as well.

Well, this is an open source project, so I would recommend you contribute if you have recommendations.

**Comment by macmade** [comment]
GitHub is not a marketplace for apps, nor a tech support site.
This is a personal, ongoing project.

if something is not good for you, you can fork and modify, or find another project.
