### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by phistep** [macmade/QEMU-Manager#5]
Maybe you could add a "Build Instructions" section into the REAMDE?

> ### Build Instructions
> 1. Clone the repository
>    ```
>    git clone https://github.com/macmade/QEMU-Manager/
>    ```
> 2. Update the submodules
>    ```
>    git submodule init
>    git submodule update
>    ```
> Open `QEMU-Manager.xcodeproj` in Xcode
> 3. Turn off code signing
> <img width="605" alt="Screenshot 2021-11-07 at 16 15 48" src="https://user-images.githubusercontent.com/544642/140650939-58e56ecc-0d5f-4fa1-a216-8e359fe44569.png">
> 4. Build <kbd>⇧⌘B</kbd>

**Comment by macmade** [comment]
Cloning a repository and building with Xcode should be pretty obvious steps in my humble opinion.

I don’t think it’s worth adding this in the read me file.

**Comment by mohamed-ea** [comment]
thanks @phistep , being a web developer this was not obvious for me.
