### ISSUE TITLE
Build, please

### ISSUE THREAD

**Issue by mauricio-ricalde** [macmade/QEMU-Manager#7]
Hi, I went to the project webpage and try to download the manager. Unfortunately, there's no build. Could you please make a build of your manager? It looks like a really good app, but I'm no developer, and can't get it compiled. Thanks.

**Comment by macmade** [comment]
Thanks for the comment.
Unfortunately the project is not finished yet, so there’s currently no build available.

**Comment by mauricio-ricalde** [comment]
Well, I'll look forward to it, looks amazing. Thank you!
