### ISSUE TITLE
Can't build on macOS 10.15

### ISSUE THREAD

**Issue by ceeGull** [macmade/QEMU-Manager#8]
![Screen Shot 2022-03-01 at 8 42 04 PM](https://user-images.githubusercontent.com/42948046/156278941-600970f1-b633-4671-8451-b25dc7687a3e.png)

**Comment by ceeGull** [comment]
I figured it out but there is another issue is that is this..
![Screen Shot 2022-03-01 at 9 06 17 PM](https://user-images.githubusercontent.com/42948046/156280857-df5b1746-bbf5-437b-98fe-f57043247d12.png)
.

**Comment by macmade** [comment]
Which version of Xcode are you using?

**Comment by ceeGull** [comment]
11.5

**Comment by macmade** [comment]
Please use an up-to-date version.
Closing for now.
